name: Deploy to Firebase Hosting on merge

on:
  push:
    branches:
      - test-app
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4  # Set up Node.js
        with:
          node-version: '18'

      - run: npm ci
      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TEST_TASK_18445 }}
          channelId: live
          projectId: test-task-18445
